In [ ]:
import pandas as pd
import os
from langchain_neo4j import GraphCypherQAChain, Neo4jGraph
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain_openai import ChatOpenAI
from langchain_core.documents import Document
from langchain_community.llms import Ollama
from dotenv import load_dotenv
from langchain_community.callbacks import get_openai_callback

from neo4j import GraphDatabase
from neo4j_graphrag.llm import OpenAILLM
from neo4j_graphrag.embeddings import OpenAIEmbeddings
from neo4j_graphrag.retrievers import VectorRetriever, VectorCypherRetriever
from neo4j_graphrag.generation import GraphRAG
from neo4j_graphrag.schema import get_schema

d:\GitHub\muict_thai_legal_RAG_GraphRAG\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Knowledge Graph Construction

In [5]:
llm = ChatOpenAI(api_key=os.getenv("openrouter_API_key") ,temperature=0, model="openai/gpt-4o-mini", base_url="https://openrouter.ai/api/v1")

# llm = Ollama(model="llama3", ) # Tested with llama3


# allowed_nodes = [
#     "Law",              # ชื่อกฎหมาย (เช่น ป.พ.พ., พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล)
#     "Section",          # มาตรา
#     "LegalElement",     # องค์ประกอบ (เช่น "เจตนา", "ประมาท", "โดยทุจริต")
#     "Exception",        # ข้อยกเว้น (สำคัญมากสำหรับกฎหมายไทย)
#     "Penalty",          # บทลงโทษ
#     "Subject",          # ตัวละครในกฎหมาย (เช่น เจ้าพนักงาน, ผู้รับมอบอำนาจ, ผู้บริโภค)
#     "LegalConsequence"  # ผลทางกฎหมาย (เช่น โมฆะ, ระงับ, สิ้นสุด)
# ]

# 3. กำหนด Relationships ให้ครอบคลุมตรรกะทางกฎหมาย
# allowed_relationships = [
#     ("Law", "CONTAINS", "Section"),
#     ("Section", "HAS_ELEMENT", "LegalElement"),  # มาตรานี้มีองค์ประกอบอะไรบ้าง
#     ("Section", "HAS_EXCEPTION", "Exception"),   # มาตรานี้มีข้อยกเว้นคืออะไร
#     ("Section", "PUNISHED_BY", "Penalty"),       # บทลงโทษของมาตรานี้
#     ("Section", "CROSS_REFERENCE", "Section"),   # การอ้างถึงมาตราอื่น (ใช้แทน CITES/REFERENCES)
#     ("LegalElement", "LEADS_TO", "LegalConsequence"), # องค์ประกอบครบถ้วนนำไปสู่ผลทางกฎหมาย
#     ("Subject", "HAS_DUTY", "LegalElement"),     # บุคคลมีหน้าที่ต้องทำอะไร
#     ("Exception", "OVERRIDES", "Section")        # ข้อยกเว้นที่ไปหักล้างหลักการในมาตรา
# ]

# 4. กำหนด Properties (เก็บเฉพาะข้อมูลที่เป็น Metadata จริงๆ)
# ข้อมูลที่เป็นเนื้อหาสำคัญควรแยกเป็น Node เพื่อความ Rich ของ GraphRAG
# node_properties = ["law_name", "section_num", "text"]

llm_transformer = LLMGraphTransformer(llm=llm,) # Model ต้องรองรับ tool เพื่อรองรับ Node properties
# llm_transformer = LLMGraphTransformer(llm=llm,allowed_nodes=allowed_nodes, allowed_relationships=allowed_relationships, node_properties=node_properties,) # Model ต้องรองรับ tool เพื่อรองรับ Node properties

In [4]:
from neo4j import GraphDatabase
load_dotenv(dotenv_path="../.env")

URI = os.getenv("NEO4J_URI")
USERNAME = os.getenv("NEO4J_USERNAME")
PASSWORD = os.getenv("NEO4J_PASSWORD")
DATABASE_NAME = os.getenv("NEO4J_DATABASE")


with GraphDatabase.driver(URI, auth=(USERNAME, PASSWORD)) as driver:
    # 2. Verify connectivity to ensure a connection can be established
    driver.verify_connectivity()
    print("Connection established successfully.")
    
graph = Neo4jGraph(url=URI, username=USERNAME, password=PASSWORD,database=DATABASE_NAME, enhanced_schema=True)

Connection established successfully.

In [ ]:
df = pd.read_parquet('../data/processed/nitibench_cleaned_2026-03-17.parquet')
df.head()

,law_name,section_content,section_num
0,พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546,พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มา...,132
1,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5\nถ้าผู...,1598/5
2,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 876\nถ้าผู้รั...,876
3,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1030\nถ้าผู้เ...,1030
4,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 849\nการรับเง...,849

In [18]:
df[df['section_content'].str.contains('หมวด')].head().to_csv('test.csv')

In [19]:
len(df)

3833

In [20]:
df.iloc[:10,:]

,law_name,section_content,section_num
0,พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546,พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มา...,132
1,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5\nถ้าผู...,1598/5
2,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 876\nถ้าผู้รั...,876
3,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1030\nถ้าผู้เ...,1030
4,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 849\nการรับเง...,849
5,พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558,พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558 มาต...,9
6,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 565\nการเช่าถ...,565
7,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/26\nผู้เ...,1598/26
8,พระราชบัญญัติการบัญชี พ.ศ. 2543,พระราชบัญญัติการบัญชี พ.ศ. 2543 มาตรา 21 ในการ...,21
9,ประมวลกฎหมายแพ่งและพาณิชย์,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 193\nในกรณีดั...,193

In [ ]:
# text = ""
# col = df.columns.to_list()
# for i in range(10):
#     sub_text = ""
#     for j in range(len(col)-1):
#         sub_text += df.iloc[i, j]
#     text += sub_text
#     text += "\n"
# print(text)

พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5
ถ้าผู้อยู่ในปกครองรู้จักผิดชอบและมีอายุไม่ต่ำกว่าสิบห้าปีบริบูรณ์เมื่อผู้ปกครองจะทำกิจการใดที่สำคัญ ให้ปรึกษาหารือผู้อยู่ในปกครองก่อนเท่าที่จะทำได้
การที่ผู้อยู่ในปกครองได้ยินยอมด้วยนั้นหาคุ้มผู้ปกครองให้พ้นจากความรับผิดไม่
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 876
ถ้าผู้รับประกันภัยต้องคำพิพากษาให้เป็นคนล้มละลาย ผู้เอาประกันภัยจะเรียกให้หาประกันอันสมควรให้แก่ตนก็ได้ หรือจะบอกเลิกสัญญาเสียก็ได้
ถ้าผู้เอาประกันภัยต้องคำพิพากษาให้เป็นคนล้มละลาย ท่านให้ใช้วิธีเดียวกันนี้บังคับตามควรแก่เรื่อง แต่กระนั้นก็ดี ถ้าเบี้ยประกันภัยได้ส่งแล้วเต็มจำนวนเพื่ออายุประกันภัยเป็นระยะเวลามากน้อยเท่าใดไซร้ ท่านห้ามมิให้ผู้รับประกันภัยบอกเลิกสัญญาก่อนระยะเวลานั้นสุดลง
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1030
ถ้าผู้เป็นหุ้นส่วนคนหนึ่งให้กรรมสิทธิ์ในทรัพย์สินอันใดอันหนึ่งเป็นการลงหุ้นด้วยไซร้ ความเกี่ยวพันระหว่างผู้เป็นหุ้นส่วนคนนั้นกับห้างหุ้นส่วนในเรื่องส่งมอบและซ่อมแซมก็ดี ความรับผิดเพื่อชำรุดบกพร่องก็ดี ความรับผิดเพื่อการรอนสิทธิก็ดี ข้อยกเว้นความรับผิดก็ดี ท่านให้บังคับตามบทบัญญัติแห่งประมวลกฎหมายนี้ ว่าด้วยซื้อขาย
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 849
การรับเงินหรือรับชำระหนี้อันจะพึงชำระตามสัญญานั้น ท่านให้สันนิษฐานไว้ก่อนว่านายหน้าย่อมไม่มีอำนาจที่จะรับแทนผู้เป็นคู่สัญญา
พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558 มาตรา 9 ผู้ให้หลักประกันจะนำทรัพย์สินที่ตนมีสิทธิอยู่ในปัจจุบันหรือที่จะได้มาในอนาคตตามสัญญาหรือนิติสัมพันธ์ใด ๆ มาใช้เป็นหลักประกันก็ได้ แต่สิทธิเหนือทรัพย์สินอันเป็นวัตถุแห่งสิทธิที่เป็นหลักประกันตามสัญญาจะมีขึ้นเมื่อผู้ให้หลักประกันได้มาซึ่งทรัพย์สินนั้น
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 565
การเช่าถือสวนนั้น ท่านให้สันนิษฐานไว้ก่อนว่าเช่ากันปีหนึ่ง
การเช่านาก็ให้สันนิษฐานไว้ก่อนว่าเช่ากันตลอดฤดูทำนาปีหนึ่ง
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/26
ผู้เยาว์ที่เป็นบุตรบุญธรรมของบุคคลใดอยู่จะเป็นบุตรบุญธรรมของบุคคลอื่นอีกในขณะเดียวกันไม่ได้ เว้นแต่เป็นบุตรบุญธรรมของคู่สมรสของผู้รับบุตรบุญธรรม
ถ้าคู่สมรสฝ่ายหนึ่งจะจดทะเบียนรับผู้เยาว์ซึ่งเป็นบุตรบุญธรรมของคู่สมรสอีกฝ่ายหนึ่งเป็นบุตรบุญธรรมของตนด้วยจะต้องได้รับความยินยอมของคู่สมรสซึ่งเป็นผู้รับบุตรบุญธรรมอยู่แล้วและมิให้นำมาตรา 1598/21 มาใช้บังคับ
พระราชบัญญัติการบัญชี พ.ศ. 2543พระราชบัญญัติการบัญชี พ.ศ. 2543 มาตรา 21 ในการลงรายการในบัญชี ผู้ทำบัญชีต้องปฏิบัติ ดังต่อไปนี้
(1) ลงรายการเป็นภาษาไทย หากลงรายการเป็นภาษาต่างประเทศให้มีภาษาไทยกำกับ หรือลงรายการเป็นรหัสบัญชีให้มีคู่มือแปลรหัสที่เป็นภาษาไทยไว้
(2) เขียนด้วยหมึก ดีดพิมพ์ ตีพิมพ์ หรือทำด้วยวิธีอื่นใดที่ได้ผลในทำนองเดียวกัน
ประมวลกฎหมายแพ่งและพาณิชย์ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 193
ในกรณีดังต่อไปนี้ ฝ่ายลูกหนี้จะถือเอาประโยชน์แห่งเงื่อนเวลาเริ่มต้นหรือเงื่อนเวลาสิ้นสุดมิได้
(1) ลูกหนี้ถูกศาลสั่งพิทักษ์ทรัพย์เด็ดขาดตามกฎหมายว่าด้วยล้มละลาย
(2) ลูกหนี้ไม่ให้ประกันในเมื่อจำต้องให้
(3) ลูกหนี้ได้ทำลาย หรือทำให้ลดน้อยถอยลงซึ่งประกันอันได้ให้ไว้
(4) ลูกหนี้นำทรัพย์สินของบุคคลอื่นมาให้เป็นประกันโดยเจ้าของทรัพย์สินนั้นมิได้ยินยอมด้วย

In [58]:
def batch_document_append(df,start=0, end=len(df)):
    documents = []
    for index, row in df.iloc[start:end,:].iterrows():
        # สร้างเนื้อหาที่มีบริบทชัดเจนในตัวเอง
        content = f"กฎหมาย: {row['law_name']}\nมาตรา: {row['section_num']}\nเนื้อหา: {row['section_content']}"
        
        # เก็บ Metadata เพื่อใช้ในภายหลัง
        metadata = {
            "law_name": row['law_name'],
            "section_num": str(row['section_num']),
        }
        documents.append(Document(page_content=content, metadata=metadata))
    return documents

documents = batch_document_append(df, start=0, end=50)
documents

[Document(metadata={'law_name': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', 'section_num': '132'}, page_content='กฎหมาย: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546\nมาตรา: 132\nเนื้อหา: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1598/5'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1598/5\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5\nถ้าผู้อยู่ในปกครองรู้จักผิดชอบและมีอายุไม่ต่ำกว่าสิบห้าปีบริบูรณ์เมื่อผู้ปกครองจะทำกิจการใดที่สำคัญ ให้ปรึกษาหารือผู้อยู่ในปกครองก่อนเท่าที่จะทำได้\nการที่ผู้อยู่ในปกครองได้ยินยอมด้วยนั้นหาคุ้มผู้ปกครองให้พ้นจากความรับผิดไม่'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '876'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 876\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 876\nถ้าผู้รับประกันภัยต้องคำพิพากษาให้เป็นคนล้มละลาย ผู้เอาประกันภัยจะเรียกให้หาประกันอันสมควรให้แก่ตนก็ได้ หรือจะบอกเลิกสัญญาเสียก็ได้\nถ้าผู้เอาประกันภัยต้องคำพิพากษาให้เป็นคนล้มละลาย ท่านให้ใช้วิธีเดียวกันนี้บังคับตามควรแก่เรื่อง แต่กระนั้นก็ดี ถ้าเบี้ยประกันภัยได้ส่งแล้วเต็มจำนวนเพื่ออายุประกันภัยเป็นระยะเวลามากน้อยเท่าใดไซร้ ท่านห้ามมิให้ผู้รับประกันภัยบอกเลิกสัญญาก่อนระยะเวลานั้นสุดลง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1030'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1030\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1030\nถ้าผู้เป็นหุ้นส่วนคนหนึ่งให้กรรมสิทธิ์ในทรัพย์สินอันใดอันหนึ่งเป็นการลงหุ้นด้วยไซร้ ความเกี่ยวพันระหว่างผู้เป็นหุ้นส่วนคนนั้นกับห้างหุ้นส่วนในเรื่องส่งมอบและซ่อมแซมก็ดี ความรับผิดเพื่อชำรุดบกพร่องก็ดี ความรับผิดเพื่อการรอนสิทธิก็ดี ข้อยกเว้นความรับผิดก็ดี ท่านให้บังคับตามบทบัญญัติแห่งประมวลกฎหมายนี้ ว่าด้วยซื้อขาย'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '849'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 849\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 849\nการรับเงินหรือรับชำระหนี้อันจะพึงชำระตามสัญญานั้น ท่านให้สันนิษฐานไว้ก่อนว่านายหน้าย่อมไม่มีอำนาจที่จะรับแทนผู้เป็นคู่สัญญา'),
 Document(metadata={'law_name': 'พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558', 'section_num': '9'}, page_content='กฎหมาย: พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558\nมาตรา: 9\nเนื้อหา: พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558 มาตรา 9 ผู้ให้หลักประกันจะนำทรัพย์สินที่ตนมีสิทธิอยู่ในปัจจุบันหรือที่จะได้มาในอนาคตตามสัญญาหรือนิติสัมพันธ์ใด ๆ มาใช้เป็นหลักประกันก็ได้ แต่สิทธิเหนือทรัพย์สินอันเป็นวัตถุแห่งสิทธิที่เป็นหลักประกันตามสัญญาจะมีขึ้นเมื่อผู้ให้หลักประกันได้มาซึ่งทรัพย์สินนั้น'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '565'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 565\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 565\nการเช่าถือสวนนั้น ท่านให้สันนิษฐานไว้ก่อนว่าเช่ากันปีหนึ่ง\nการเช่านาก็ให้สันนิษฐานไว้ก่อนว่าเช่ากันตลอดฤดูทำนาปีหนึ่ง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1598/26'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1598/26\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/26\nผู้เยาว์ที่เป็นบุตรบุญธรรมของบุคคลใดอยู่จะเป็นบุตรบุญธรรมของบุคคลอื่นอีกในขณะเดียวกันไม่ได้ เว้นแต่เป็นบุตรบุญธรรมของคู่สมรสของผู้รับบุตรบุญธรรม\nถ้าคู่สมรสฝ่ายหนึ่งจะจดทะเบียนรับผู้เยาว์ซึ่งเป็นบุตรบุญธรรมของคู่สมรสอีกฝ่ายหนึ่งเป็นบุตรบุญธรรมของตนด้วยจะต้องได้รับความยินยอมของคู่สมรสซึ่งเป็นผู้รับบุตรบุญธรรมอยู่แล้วและมิให้นำมาตรา 1598/21 มาใช้บังคับ'),
 Document(metadata={'law_name': 'พระราชบัญญัติการบัญชี พ.ศ. 2543', 'section_num': '21'}, page_content='กฎหมาย: พระราชบัญญัติการบัญชี พ.ศ. 2543\nมาตรา: 21\nเนื้อหา: พระราชบัญญัติการบัญชี พ.ศ. 2543 มาตรา 21 ในการลงรายการในบัญชี ผู้ทำบัญชีต้องปฏิบัติ ดังต่อไปนี้\n(1) ลงรายการเป็นภาษาไทย หากลงรายการเป็นภาษาต่างประเทศให้มีภาษาไทยกำกับ หรือลงรายการเป็นรหัสบัญชีให้มีคู่มือแปลรหัสที่เป็นภาษาไทยไว้\n(2) เขียนด้วยหมึก ดีดพิมพ์ ตีพิมพ์ หรือทำด้วยวิธีอื่นใดที่ได้ผลในทำนองเดียวกัน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '193'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 193\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 193\nในกรณีดังต่อไปนี้ ฝ่ายลูกหนี้จะถือเอาประโยชน์แห่งเงื่อนเวลาเริ่มต้นหรือเงื่อนเวลาสิ้นสุดมิได้\n(1) ลูกหนี้ถูกศาลสั่งพิทักษ์ทรัพย์เด็ดขาดตามกฎหมายว่าด้วยล้มละลาย\n(2) ลูกหนี้ไม่ให้ประกันในเมื่อจำต้องให้\n(3) ลูกหนี้ได้ทำลาย หรือทำให้ลดน้อยถอยลงซึ่งประกันอันได้ให้ไว้\n(4) ลูกหนี้นำทรัพย์สินของบุคคลอื่นมาให้เป็นประกันโดยเจ้าของทรัพย์สินนั้นมิได้ยินยอมด้วย'),
 Document(metadata={'law_name': 'ประมวลรัษฎากร', 'section_num': '119'}, page_content='กฎหมาย: ประมวลรัษฎากร\nมาตรา: 119\nเนื้อหา: ประมวลรัษฎากร มาตรา 119 ตราสารซึ่งเจ้าพนักงานรัฐบาลหรือเทศบาลต้องลงนามหรือรับรู้ก็ดี ตราสารซึ่งต้องทำต่อหน้าเจ้าพนักงานรัฐบาลหรือเทศบาลก็ดี ตราสารซึ่งต้องให้เจ้าพนักงานรัฐบาลหรือเทศบาลลงบันทึกก็ดี ห้ามมิให้เจ้าพนักงานลงนามรับรู้ ยอมให้ทำหรือบันทึกไว้จนกว่าจะได้เสียอากรโดยปิดแสตมป์ครบจำนวนตามอัตราในบัญชีท้ายหมวดนี้ และขีดฆ่าแล้ว แต่ทั้งนี้ ไม่เป็นการเสื่อมสิทธิที่จะเรียกเงินเพิ่มอากรตามมาตรา 113 และมาตรา 114'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '485'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 485\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 485\nข้อสัญญาว่าจะไม่ต้องรับผิดนั้น ไม่อาจคุ้มความรับผิดของผู้ขายในผลของการอันผู้ขายได้กระทำไปเอง หรือผลแห่งข้อความจริงอันผู้ขายได้รู้อยู่แล้วและปกปิดเสีย'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1396'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1396\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1396\nภาระจำยอมซึ่งเจ้าของรวมแห่งสามยทรัพย์คนหนึ่งได้มา หรือใช้อยู่นั้น ท่านให้ถือว่าเจ้าของรวมได้มาหรือใช้อยู่ด้วยกันทุกคน'),
 Document(metadata={'law_name': 'ประมวลรัษฎากร', 'section_num': '86/3'}, page_content='กฎหมาย: ประมวลรัษฎากร\nมาตรา: 86/3\nเนื้อหา: ประมวลรัษฎากร มาตรา 86/3 ในการขายทอดตลาดตามมาตรา 83/5 ให้ผู้ทอดตลาดที่มิใช่ส่วนราชการซึ่งขายทรัพย์สินของผู้ประกอบการจดทะเบียนออกใบกำกับภาษีหรือใบรับตามมาตรา 105 แล้วแต่กรณี ในนามของผู้ประกอบการจดทะเบียนเจ้าของทรัพย์สิน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '582'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 582\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 582\nถ้าคู่สัญญาไม่ได้กำหนดลงไว้ในสัญญาว่าจะจ้างกันนานเท่าไร ท่านว่าฝ่ายใดฝ่ายหนึ่งจะเลิกสัญญาด้วยการบอกกล่าวล่วงหน้าในเมื่อถึงหรือก่อนจะถึงกำหนดจ่ายสินจ้างคราวใดคราวหนึ่ง เพื่อให้เป็นผลเลิกสัญญากันเมื่อถึงกำหนดจ่ายสินจ้างคราวถัดไปข้างหน้าก็อาจทำได้ แต่ไม่จำต้องบอกกล่าวล่วงหน้ากว่าสามเดือน\nอนึ่ง ในเมื่อบอกกล่าวดังว่านี้ นายจ้างจะจ่ายสินจ้างแก่ลูกจ้างเสียให้ครบจำนวนที่จะต้องจ่ายจนถึงเวลาเลิกสัญญาตามกำหนดที่บอกกล่าวนั้นทีเดียว แล้วปล่อยลูกจ้างจากงานเสียในทันทีก็อาจทำได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1262'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1262\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1262\nถ้ามีมติของที่ประชุมใหญ่หรือคำบังคับของศาลให้อำนาจผู้ชำระบัญชีให้ทำการแยกกันได้ ท่านว่าต้องนำความจดทะเบียนภายในสิบสี่วันนับแต่วันลงมติหรือออกคำบังคับนั้น'),
 Document(metadata={'law_name': 'ประมวลรัษฎากร', 'section_num': '82/2'}, page_content='กฎหมาย: ประมวลรัษฎากร\nมาตรา: 82/2\nเนื้อหา: ประมวลรัษฎากร มาตรา 82/2 ในกรณีผู้ประกอบการอยู่นอกราชอาณาจักร ให้ผู้มีหน้าที่รับผิดชอบในการประกอบกิจการ รวมตลอดถึง ลูกจ้าง หรือผู้ทำการแทนซึ่งมีอำนาจในการจัดการแทนโดยตรงหรือโดยปริยายที่อยู่ในราชอาณาจักร เป็นผู้มีหน้าที่เสียภาษีมูลค่าเพิ่มร่วมกับบุคคลตามมาตรา 82'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '386'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 386\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 386\nถ้าคู่สัญญาฝ่ายหนึ่งมีสิทธิเลิกสัญญาโดยข้อสัญญาหรือโดยบทบัญญัติแห่งกฎหมาย การเลิกสัญญาเช่นนั้นย่อมทำด้วยแสดงเจตนาแก่อีกฝ่ายหนึ่ง\nแสดงเจตนาดังกล่าวมาในวรรคก่อนนั้น ท่านว่าหาอาจจะถอนได้ไม่'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '694'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 694\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 694\nนอกจากข้อต่อสู้ซึ่งผู้ค้ำประกันมีต่อเจ้าหนี้นั้น ท่านว่าผู้ค้ำประกันยังอาจยกข้อต่อสู้ทั้งหลายซึ่งลูกหนี้มีต่อเจ้าหนี้ขึ้นต่อสู้ได้ด้วย'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1708'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1708\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1708\nเมื่อผู้ทำพินัยกรรมตายแล้ว บุคคลผู้มีส่วนได้เสียคนใดคนหนึ่งจะร้องขอให้ศาลสั่งเพิกถอนพินัยกรรมซึ่งได้ทำขึ้นเพราะเหตุข่มขู่ก็ได้ แต่หากผู้ทำพินัยกรรมยังมีชีวิตอยู่ต่อมาเกินหนึ่งปีนับแต่ผู้ทำพินัยกรรมพ้นจากการข่มขู่แล้ว จะมีการร้องขอเช่นว่านั้นไม่ได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1364'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1364\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1364\nการแบ่งทรัพย์สินพึงกระทำโดยแบ่งทรัพย์สินนั้นเองระหว่างเจ้าของรวม หรือโดยขายทรัพย์สินแล้วเอาเงินที่ขายได้แบ่งกัน\nถ้าเจ้าของรวมไม่ตกลงกันว่าจะแบ่งทรัพย์สินอย่างไรไซร้ เมื่อเจ้าของรวมคนหนึ่งคนใดขอ ศาลอาจสั่งให้เอาทรัพย์สินนั้นออกแบ่ง ถ้าส่วนที่แบ่งให้ไม่เท่ากันไซร้ จะสั่งให้ทดแทนกันเป็นเงินก็ได้ ถ้าการแบ่งเช่นว่านี้ไม่อาจทำได้หรือจะเสียหายมากนักก็ดี ศาลจะสั่งให้ขายโดยประมูลราคากันระหว่างเจ้าของรวมหรือขายทอดตลาดก็ได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '660'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 660\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 660\nถ้าผู้ฝากมิได้อนุญาต และผู้รับฝากเอาทรัพย์สินซึ่งฝากนั้นออกใช้สอยเอง หรือเอาไปให้บุคคลภายนอกใช้สอย หรือให้บุคคลภายนอกเก็บรักษาไซร้ ท่านว่าผู้รับฝากจะต้องรับผิดเมื่อทรัพย์สินซึ่งฝากนั้นสูญหายหรือบุบสลายอย่างหนึ่งอย่างใด แม้ถึงจะเป็นเพราะเหตุสุดวิสัย เว้นแต่จะพิสูจน์ได้ว่าถึงอย่างไร ๆ ทรัพย์สินนั้นก็คงจะต้องสูญหายหรือบุบสลายอยู่นั่นเอง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '369'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 369\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 369\nในสัญญาต่างตอบแทนนั้น คู่สัญญาฝ่ายหนึ่งจะไม่ยอมชำระหนี้จนกว่าอีกฝ่ายหนึ่งจะชำระหนี้ หรือขอปฏิบัติการชำระหนี้ก็ได้ แต่ความข้อนี้ท่านมิให้ใช้บังคับ ถ้าหนี้ของคู่สัญญาอีกฝ่ายหนึ่งยังไม่ถึงกำหนด'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '719'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 719\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 719\nจำนองที่ดินไม่ครอบไปถึงเรือนโรงอันผู้จำนองปลูกสร้างลงในที่ดินภายหลังวันจำนอง เว้นแต่จะมีข้อความกล่าวไว้โดยเฉพาะในสัญญาว่าให้ครอบไปถึง\nแต่กระนั้นก็ดี ผู้รับจำนองจะให้ขายเรือนโรงนั้นรวมไปกับที่ดินด้วยก็ได้ แต่ผู้รับจำนองอาจใช้บุริมสิทธิของตนได้เพียงแก่ราคาที่ดินเท่านั้น'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '878'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 878\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 878\nค่าใช้จ่ายในการตีราคาวินาศภัยนั้น ท่านว่าผู้รับประกันภัยต้องเป็นผู้ออกใช้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1129'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1129\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1129\nอันว่าหุ้นนั้นย่อมโอนกันได้โดยมิต้องได้รับความยินยอมของบริษัท เว้นแต่เมื่อเป็นหุ้นชนิดระบุชื่อลงในใบหุ้น ซึ่งมีข้อบังคับของบริษัทกำหนดไว้เป็นอย่างอื่น\nการโอนหุ้นชนิดระบุชื่อลงในใบหุ้นนั้น ถ้ามิได้ทำเป็นหนังสือและลงลายมือชื่อของผู้โอนกับผู้รับโอน มีพยานคนหนึ่งเป็นอย่างน้อยลงชื่อรับรองลายมือนั้น ๆ ด้วยแล้ว ท่านว่าเป็นโมฆะ อนึ่ง ตราสารอันนั้นต้องแถลงเลขหมายของหุ้นซึ่งโอนกันนั้นด้วย\nการโอนเช่นนี้จะนำมาใช้แก่บริษัทหรือบุคคลภายนอกไม่ได้ จนกว่าจะได้จดแจ้งการโอนทั้งชื่อและสำนักของผู้รับโอนนั้นลงในทะเบียนผู้ถือหุ้น'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '605'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 605\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 605\nถ้าการที่จ้างยังทำไม่แล้วเสร็จอยู่ตราบใด ผู้ว่าจ้างอาจบอกเลิกสัญญาได้ เมื่อเสียค่าสินไหมทดแทนให้แก่ผู้รับจ้างเพื่อความเสียหายอย่างใด ๆ อันเกิดแต่การเลิกสัญญานั้น'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '942'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 942\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 942\nอันจะบังคับให้ผู้ทรงตั๋วแลกเงินรับเงินใช้ก่อนตั๋วเงินถึงกำหนดนั้น ท่านว่าหาอาจจะทำได้ไม่\nอนึ่ง ผู้จ่ายคนใดใช้เงินไปแต่ก่อนเวลาตั๋วเงินถึงกำหนด ท่านว่าย่อมทำเช่นนั้นด้วยเสี่ยงเคราะห์ของตนเอง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '193/21'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 193/21\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 193/21\nอายุความสิทธิเรียกร้องของผู้เยาว์หรือของคนไร้ความสามารถหรือของคนเสมือนไร้ความสามารถ ที่จะฟ้องร้องผู้แทนโดยชอบธรรมหรือผู้อนุบาลหรือผู้พิทักษ์ของตนนั้น ถ้าจะครบกำหนดลงในขณะที่บุคคลดังกล่าวยังไม่ลุถึงความสามารถเต็มภูมิ หรือในระหว่างหนึ่งปีนับแต่วันที่บุคคลดังกล่าวไม่มีผู้แทนโดยชอบธรรมหรือผู้อนุบาลหรือผู้พิทักษ์ อายุความนั้นยังไม่ครบกำหนดจนกว่าจะครบหนึ่งปีนับแต่วันที่บุคคลนั้นได้ลุถึงความสามารถเต็มภูมิหรือได้มีผู้แทนโดยชอบธรรมหรือผู้อนุบาลหรือผู้พิทักษ์ แล้วแต่กรณี แต่ถ้าอายุความสิทธิเรียกร้องนั้นมีระยะเวลาน้อยกว่าหนึ่งปี ก็ให้นำกำหนดระยะเวลาที่สั้นกว่านั้นมาใช้แทนกำหนดระยะเวลาหนึ่งปีดังกล่าว'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1003'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1003\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1003\nในคดีผู้สลักหลังทั้งหลายฟ้องไล่เบี้ยกันเองและไล่เบี้ยเอาแก่ผู้สั่งจ่ายแห่งตั๋วเงิน ท่านห้ามมิให้ฟ้องคดีเมื่อพ้นเวลาหกเดือนนับแต่วันที่ผู้สลักหลังเข้าถือเอาตั๋วเงินและใช้เงิน หรือนับแต่วันที่ผู้สลักหลังนั้นเองถูกฟ้อง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '138'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 138\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 138\nทรัพย์สิน หมายความรวมทั้งทรัพย์และวัตถุไม่มีรูปร่าง ซึ่งอาจมีราคาและอาจถือเอาได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '334'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 334\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 334\nลูกหนี้มีสิทธิจะถอนทรัพย์ที่วางนั้นได้ ถ้าลูกหนี้ถอนทรัพย์นั้น ท่านให้ถือเสมือนว่ามิได้วางทรัพย์ไว้เลย\nสิทธิถอนทรัพย์นี้เป็นอันขาดในกรณีต่อไปนี้\n(1) ถ้าลูกหนี้แสดงต่อสำนักงานวางทรัพย์ว่าตนยอมละสิทธิที่จะถอน\n(2) ถ้าเจ้าหนี้แสดงต่อสำนักงานวางทรัพย์ว่าจะรับเอาทรัพย์นั้น\n(3) ถ้าการวางทรัพย์นั้นได้เป็นไปโดยคำสั่งหรืออนุมัติของศาลและได้บอกกล่าวความนั้นแก่สำนักงานวางทรัพย์'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '504'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 504\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 504\nในข้อรับผิดเพื่อการส่งของไม่ตรงตามตัวอย่าง หรือไม่ตรงตามคำพรรณนานั้น ท่านห้ามมิให้ฟ้องคดีเมื่อพ้นกำหนดปีหนึ่งนับแต่เวลาส่งมอบ'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1321'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1321\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1321\nภายในบังคับแห่งกฎหมายเฉพาะและกฎข้อบังคับในเรื่องนั้น ผู้ใดจับสัตว์ป่าได้ในที่รกร้างว่างเปล่าหรือในที่น้ำสาธารณะก็ดี หรือจับได้ในที่ดิน หรือที่น้ำมีเจ้าของโดยเจ้าของมิได้แสดงความหวงห้ามก็ดี ท่านว่าผู้นั้นเป็นเจ้าของสัตว์'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1315'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1315\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1315\nบุคคลใดสร้างโรงเรือน หรือทำการก่อสร้างอย่างอื่นซึ่งติดที่ดิน หรือเพาะปลูกต้นไม้หรือธัญชาติในที่ดินของตนด้วยสัมภาระของผู้อื่น ท่านว่าบุคคลนั้นเป็นเจ้าของสัมภาระ แต่ต้องใช้ค่าสัมภาระ'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '368'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 368\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 368\nสัญญานั้นท่านให้ตีความไปตามความประสงค์ในทางสุจริต โดยพิเคราะห์ถึงปรกติประเพณีด้วย'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1083'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1083\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1083\nการลงหุ้นของผู้เป็นหุ้นส่วนจำพวกจำกัดความรับผิดนั้น ท่านว่าต้องให้ลงเป็นเงินหรือทรัพย์สินอย่างอื่น ๆ'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '442'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 442\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 442\nถ้าความเสียหายได้เกิดขึ้นเพราะความผิดอย่างหนึ่งอย่างใดของผู้ต้องเสียหายประกอบด้วยไซร้ ท่านให้นำบทบัญญัติแห่งมาตรา 223 มาใช้บังคับ โดยอนุโลม'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1653'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1653\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1653\nผู้เขียน หรือพยานในพินัยกรรมจะเป็นผู้รับทรัพย์ตามพินัยกรรมนั้นไม่ได้\nให้ใช้บทบัญญัติในวรรคก่อนบังคับแก่คู่สมรสของผู้เขียนหรือพยานในพินัยกรรมด้วย\nพนักงานเจ้าหน้าที่ซึ่งได้จดข้อความแห่งพินัยกรรมที่พยานนำมาแจ้งตามมาตรา 1663 ให้ถือว่าเป็นผู้เขียนพินัยกรรมตามความหมายแห่งมาตรานี้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '584'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 584\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 584\nถ้าจ้างแรงงานรายใดมีสาระสำคัญอยู่ที่ตัวบุคคลผู้เป็นนายจ้าง ท่านว่าสัญญาจ้างเช่นนั้นย่อมระงับไปด้วยมรณะแห่งนายจ้าง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1424'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1424\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1424\nผู้ทรงสิทธิเก็บกินจำต้องสงวนภาวะแห่งทรัพย์สินมิให้เปลี่ยนไปในสาระสำคัญ กับต้องบำรุงรักษาปกติและซ่อมแซมเล็กน้อยด้วย\nถ้าจำเป็นต้องซ่อมแซมใหญ่ หรือมีการสำคัญอันต้องทำเพื่อรักษาทรัพย์สินไซร้ ท่านว่าผู้ทรงสิทธิเก็บกินต้องแจ้งแก่เจ้าของทรัพย์สินโดยพลัน และต้องยอมให้จัดทำการนั้น ๆ ไป ถ้าเจ้าของทรัพย์สินละเลยเสีย ท่านว่าผู้ทรงสิทธิเก็บกินจะจัดทำการนั้นไปโดยให้เจ้าของทรัพย์สินออกค่าใช้จ่ายก็ได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1649'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1649\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1649\nผู้จัดการมรดกซึ่งผู้ตายตั้งไว้ย่อมมีอำนาจและหน้าที่ในอันที่จะจัดการทำศพของผู้ตาย เว้นแต่ผู้ตายจะได้ตั้งบุคคลอื่นไว้โดยเฉพาะให้จัดการดังว่านั้น\nถ้าผู้ตายมิได้ตั้งผู้จัดการมรดกหรือบุคคลใดไว้ให้เป็นผู้จัดการทำศพ หรือทายาทมิได้มอบหมายตั้งให้บุคคลใดเป็นผู้จัดการทำศพ บุคคลผู้ได้รับทรัพย์มรดกโดยพินัยกรรมหรือโดยสิทธิโดยธรรมเป็นจำนวนมากที่สุด เป็นผู้มีอำนาจและตกอยู่ในหน้าที่ต้องจัดการทำศพ เว้นแต่ศาลจะเห็นเป็นการสมควรตั้งบุคคลอื่นให้จัดการเช่นนั้น ในเมื่อบุคคลผู้มีส่วนได้เสียคนใดคนหนึ่งร้องขอขึ้น'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1428'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1428\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1428\nคดีอันเกี่ยวกับสิทธิเก็บกินในระหว่างเจ้าของทรัพย์สินกับผู้ทรงสิทธิเก็บกิน หรือผู้รับโอนนั้น ท่านห้ามมิให้ฟ้องเมื่อเกินปีหนึ่งนับแต่วันสิทธิเก็บกินสุดสิ้นลง แต่ในคดีที่เจ้าของทรัพย์สินเป็นโจทก์นั้น ถ้าเจ้าของไม่อาจรู้ว่าสิทธิเก็บกินสุดสิ้นลงเมื่อใด ท่านให้นับอายุความปีหนึ่งนั้นตั้งแต่เวลาที่เจ้าของทรัพย์สินได้รู้ หรือควรรู้ว่าสิทธิเก็บกินสุดสิ้นลง'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'section_num': '1047'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1047\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1047\nถ้าชื่อของผู้เป็นหุ้นส่วนซึ่งออกจากหุ้นส่วนไปแล้วยังคงใช้เรียกขานติดเป็นชื่อห้างหุ้นส่วนอยู่ ท่านว่าผู้เป็นหุ้นส่วนนั้นชอบที่จะเรียกให้งดใช้ชื่อของตนเสียได้'),

In [24]:
import time 

with get_openai_callback() as cb:
    start_time = time.perf_counter()

    # documents = [Document(page_content=text)]
    graph_documents = llm_transformer.convert_to_graph_documents(documents)

    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    print(f"Elapsed time: {elapsed_time:.4f} seconds")
    print(f"Total Tokens: {cb.total_tokens}")
    print(f"Prompt Tokens: {cb.prompt_tokens}")
    print(f"Completion Tokens: {cb.completion_tokens}")
    print(f"Total Cost (USD): ${cb.total_cost}")

Elapsed time: 270.3324 seconds
Total Tokens: 0
Prompt Tokens: 0
Completion Tokens: 0
Total Cost (USD): $0.0

In [25]:
for node in graph_documents[0].nodes:
    print(node)

id='ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54' type='Entity' properties={}
id='มาตรา 132' type='Clause' properties={}
id='ใบอนุญาต' type='Document' properties={}
id='พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546' type='Law' properties={}
id='มาตรา 54' type='Clause' properties={}

In [26]:
for relationship in graph_documents[0].relationships:
    print(relationship)

source=Node(id='พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', type='Law', properties={}) target=Node(id='มาตรา 132', type='Clause', properties={}) type='DEFINED_BY' properties={}
source=Node(id='พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', type='Law', properties={}) target=Node(id='ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54', type='Entity', properties={}) type='REGULATES' properties={}
source=Node(id='พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', type='Law', properties={}) target=Node(id='ใบอนุญาต', type='Document', properties={}) type='REGULATES' properties={}
source=Node(id='พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', type='Law', properties={}) target=Node(id='มาตรา 54', type='Clause', properties={}) type='REGULATES' properties={}

In [ ]:
graph.add_graph_documents(graph_documents, include_source=True)

## Querying the graph

### Text to Cypher Approach

In [62]:
schema = graph.get_schema
schema

'Node properties:\n- **Law**\n  - `id`: STRING Available options: [\'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546\', \'ประมวลกฎหมายแพ่งและพาณิชย์\', \'พระราชบัญญัติการบัญชี พ.ศ. 2543\', \'กฎหมายว่าด้วยล้มละลาย\', \'ประมวลรัษฎากร\', \'กฎหมาย\']\n- **Clause**\n  - `id`: STRING Example: "มาตรา 132"\n- **Laws**\n  - `id`: STRING Available options: [\'พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558\', \'พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558 มาตรา 9\', \'ประมวลกฎหมายแพ่งและพาณิชย์\']\n- **Section**\n  - `id`: STRING Example: "มาตรา 1598/5"\n- **Person**\n  - `id`: STRING Example: "ผู้เป็นหุ้นส่วนคนนั้น"\n- **Action**\n  - `id`: STRING Available options: [\'เอาทรัพย์สินออกแบ่ง\', \'การก่อสร้างอย่างอื่น\', \'การเพิกถอนการสมรส\']\n- **Content**\n  - `id`: STRING Available options: [\'เนื้อหา\']\n- **Right**\n  - `id`: STRING Available options: [\'เรียกให้หาประกันอันสมควร\', \'สิทธิเหนือทรัพย์สินอันเป็นวัตถุแห่งสิทธิที่เป็นหลั\', \'สิทธิเลิกสัญญา\', \'ไม่ยอมชำระหนี้\', \'ชำระหนี้\', \'จำนองที่ดิน\', \'ถอนทรัพย์ที่วางนั้นได้\']\n- **Contract**\n  - `id`: STRING Available options: [\'สัญญา\', \'ในสัญญาต่างตอบแทนนั้น\']\n- **Document**\n  - `text`: STRING Example: "กฎหมาย: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 254"\n  - `law_name`: STRING Available options: [\'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546\', \'ประมวลกฎหมายแพ่งและพาณิชย์\', \'พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558\', \'พระราชบัญญัติการบัญชี พ.ศ. 2543\', \'ประมวลรัษฎากร\']\n  - `section_num`: STRING Example: "132"\n  - `id`: STRING Example: "5706189faec3d4c887fadb06cd797b4e"\n- **Lawsuit**\n  - `id`: STRING Available options: [\'ประมวลกฎหมายแพ่งและพาณิชย์\']\n- **Concept**\n  - `id`: STRING Available options: [\'ท่านให้ถือว่าเจ้าของรวมได้มาหรือใช้อยู่ด้วยกันทุกค\', \'ภาระจำยอมซึ่งเจ้าของรวมแห่งสามยทรัพย์คนหนึ่งได้มา \', \'ทรัพย์สิน\']\n- **Legislation**\n  - `id`: STRING Available options: [\'ประมวลกฎหมายแพ่งและพาณิชย์\']\n- **Party**\n  - `id`: STRING Available options: [\'ลูกหนี้\', \'คู่สัญญาฝ่ายหนึ่ง\', \'เจ้าของรวม\', \'คู่สัญญาอีกฝ่ายหนึ่ง\', \'ผู้รับประกันภัย\', \'ผู้รับจ้าง\', \'ผู้ว่าจ้าง\', \'เจ้าหนี้\']\n- **Court**\n  - `id`: STRING Available options: [\'ศาล\']\n- **Property**\n  - `id`: STRING Available options: [\'ทรัพย์สินอันใดอันหนึ่ง\', \'ทรัพย์สิน\', \'สัมภาระของผู้อื่น\', \'สัมภาระ\']\n- **Asset**\n  - `id`: STRING Available options: [\'ทรัพย์นั้น\', \'ทรัพย์\', \'ทรัพย์สิน\']\n- **Employer**\n  - `id`: STRING Available options: [\'นายจ้าง\']\n- **Employee**\n  - `id`: STRING Available options: [\'ลูกจ้าง\']\n- **Article**\n  - `id`: STRING Available options: [\'มาตรา 386\', \'มาตรา 1525\', \'มาตรา 1513\']\n- **Organization**\n  - `id`: STRING Available options: [\'ศาล\']\n- **Age**\n  - `id`: STRING Available options: [\'สิบห้าปีบริบูรณ์\']\n- **Activity**\n  - `id`: STRING Available options: [\'(1) ขายหรือจำนองอสังหาริมทรัพย์\', \'(6) มอบข้อพิพาทให้อนุญาโตตุลาการพิจารณา\', \'(3) ให้\', \'(5) ยื่นฟ้องต่อศาล\', \'(2) ให้เช่าอสังหาริมทรัพย์กว่าสามปีขึ้นไป\', \'(4) ประนีประนอมยอมความ\']\n- **Language**\n  - `id`: STRING Available options: [\'ภาษาไทย\']\n- **Entity**\n  - `id`: STRING Available options: [\'ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อ\', \'ผู้อยู่ในปกครอง\', \'ผู้ปกครอง\']\n- **Assured**\n  - `id`: STRING Available options: [\'ผู้รับประกันภัย\']\n- **Benefit**\n  - `id`: STRING Available options: [\'ประกันอันสมควร\']\n- **Insurer**\n  - `id`: STRING Available options: [\'ผู้เอาประกันภัย\']\n- **Company**\n  - `id`: STRING Available options: [\'ห้างหุ้นส่วน\', \'บริษัท\']\n- **Category**\n  - `id`: STRING Available options: [\'กฎหมาย\']\n- **Event**\n  - `id`: STRING Available options: [\'ผู้ให้หลักประกันได้มาซึ่งทรัพย์สินนั้น\']\n- **Assumption**\n  - `id`: STRING Available options: [\'ตลอดฤดูทำนาปีหนึ่ง\', \'เช่ากันปีหนึ่ง\']\n- **Text**\n  - `id`: STRING Available options: [\'เนื้อหา ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 565\']\n- **Procedure**\n  - `id`: STRING Available options: [\'การลงรายการในบัญชี\', \'การลงรายการเป็นภาษาต่างประเทศ\', \'การแบ่งทรัพย์สิน\']\n- **Code**\n  - `id`: STRING Available options: [\'รหัสบัญชี\']\n- **Law Section**\n  - `id`: STRING Available options: [\'พระราชบัญญัติการบัญชี พ.ศ. 2543 มาตรา 21\', \'มาตรา 336\']\n- **Regulation**\n  - `id`: STRING Available options: [\'มาตรา 86/3\']\n- **Transaction**\n  - `id`: STRING Available options: [\'การขายทอดตลาดตามมาตรา 83/5\']\n- **Authority**\n  - `id`: STRING Available options: [\'อำนาจผู้ชำระบัญชี\', \'ศาล\']\n- **Meeting**\n  - `id`: STRING Available options: [\'ที่ประชุมใหญ่\']\n- **Order**\n  - `id`: STRING Available options: [\'คำบังคับของศาล\']\n- **Will**\n  - `id`: STRING Available options: [\'พินัยกรรม\']\n- **Land**\n  - `id`: STRING Available options: [\'ที่ดิน\']\n- **Cost**\n  - `id`: STRING Available options: [\'ค่าใช้จ่ายในการตีราคาวินาศภัยนั้น\']\n- **Stock**\n  - `id`: STRING Available options: [\'หุ้นนั้น\', \'หุ้นชนิดระบุชื่อลงในใบหุ้น\']\n- **Condition**\n  - `id`: STRING Available options: [\'โดยมิต้องได้รับความยินยอมของบริษัท\']\n- **Payment**\n  - `id`: STRING Available options: [\'ค่าสินไหมทดแทน\']\n- **Agreement**\n  - `id`: STRING Available options: [\'สัญญา\']\n- **Time Period**\n  - `id`: STRING Available options: [\'ฟ้องคดีเมื่อพ้นเวลาหกเดือนนับแต่วันที่ผู้สลักหลังเ\']\n- **Court Case**\n  - `id`: STRING Available options: [\'คดีผู้สลักหลังทั้งหลายฟ้องไล่เบี้ยกันเองและไล่เบี้\']\n- **Organisation**\n  - `id`: STRING Available options: [\'สำนักงานวางทรัพย์\']\n- **Notification**\n  - `id`: STRING Available options: [\'การวางทรัพย์นั้น\']\n- **Article or Section**\n  - `id`: STRING Available options: [\'มาตรา 1321\']\n- **Laws and Regulations**\n  - `id`: STRING Available options: [\'ประมวลกฎหมายแพ่งและพาณิชย์\']\n- **Structure**\n  - `id`: STRING Available options: [\'โรงเรือน\']\n- **Body**\n  - `id`: STRING Available options: [\'ศพ\']\n- **Responsibility**\n  - `id`: STRING Available options: [\'อำนาจและหน้าที่\']\n- **Inheritance**\n  - `id`: STRING Available options: [\'ทรัพย์มรดก\']\n- **Consequence**\n  - `id`: STRING Available options: [\'ความเสียหาย\']\n- **Compensation**\n  - `id`: STRING Available options: [\'ค่าทดแทน\']\n- **Property or Income**\n  - `id`: STRING Available options: [\'ทรัพย์สินหรือจากการงาน\']\n- **Living Expenses**\n  - `id`: STRING Available options: [\'ค่าเลี้ยงชีพ\']\n- **Legal Topic**\n  - `id`: STRING Available options: [\'กฎหมาย\']\n- **Agent**\n  - `id`: STRING Available options: [\'ตัวแทน\']\n- **Case**\n  - `id`: STRING Available options: [\'การเช่นอย่าง\']\n- **Partner**\n  - `id`: STRING Available options: [\'ผู้เป็นหุ้นส่วนคนหนึ่ง\']\n- **Business Activity**\n  - `id`: STRING Available options: [\'การงานของห้างหุ้นส่วน\']\nRelationship properties:\n\nThe relationships:\n(:Law)-[:REGULATES]->(:Clause)\n(:Law)-[:REGULATES]->(:Document)\n(:Law)-[:REGULATES]->(:Entity)\n(:Law)-[:REGULATES]->(:Contract)\n(:Law)-[:REGULATES]->(:Activity)\n(:Law)-[:REGULATES]->(:Procedure)\n(:Law)-[:DEFINED_BY]->(:Clause)\n(:Law)-[:DEFINED_BY]->(:Section)\n(:Law)-[:CONTAINS]->(:Entity)\n(:Law)-[:CONTAINS]->(:Section)\n(:Law)-[:CONTAINS]->(:Article)\n(:Law)-[:CONTAINS]->(:Content)\n(:Law)-[:CONTAINS]->(:Clause)\n(:Law)-[:CONTAINS]->(:Text)\n(:Law)-[:CONTAINS]->(:Procedure)\n(:Law)-[:HAS_SECTION]->(:Section)\n(:Law)-[:RELATED_TO]->(:Clause)\n(:Law)-[:RELATED_TO]->(:Section)\n(:Law)-[:RELATED_TO]->(:Law)\n(:Law)-[:DEFINES]->(:Concept)\n(:Law)-[:DEFINES]->(:Section)\n(:Law)-[:DEFINES]->(:Court Case)\n(:Law)-[:DEFINES]->(:Regulation)\n(:Law)-[:APPLIES_TO]->(:Case)\n(:Law)-[:APPLIES_TO]->(:Transaction)\n(:Law)-[:REFERS_TO]->(:Clause)\n(:Law)-[:REFERS_TO]->(:Article)\n(:Law)-[:REFERS_TO]->(:Section)\n(:Law)-[:REFERS_TO]->(:Will)\n(:Law)-[:REFERS_TO]->(:Content)\n(:Law)-[:RESTRICTS]->(:Time Period)\n(:Laws)-[:REGULATES]->(:Category)\n(:Laws)-[:PART_OF]->(:Laws)\n(:Laws)-[:CONTAINS]->(:Clause)\n(:Laws)-[:CONTAINS]->(:Article)\n(:Laws)-[:DEFINES]->(:Cost)\n(:Laws)-[:DEFINES]->(:Right)\n(:Section)-[:EXPLAINED_BY]->(:Document)\n(:Person)-[:HAS_RELATIONSHIP]->(:Company)\n(:Person)-[:GIVES_RIGHTS]->(:Property)\n(:Person)-[:CAN_USE_AS_COLLATERAL]->(:Property)\n(:Person)-[:GIVES_RIGHTS_TO]->(:Partner)\n(:Person)-[:MAKES_ASSUMPTION]->(:Assumption)\n(:Person)-[:ADOPTS_CHILD]->(:Person)\n(:Person)-[:OBTAINS_ACKNOWLEDGMENT_FROM]->(:Person)\n(:Person)-[:CREATE]->(:Structure)\n(:Person)-[:PERFORM]->(:Action)\n(:Person)-[:USE]->(:Property)\n(:Person)-[:IS_ADOPTEE_OF]->(:Person)\n(:Person)-[:CANNOT_BE_ADOPTED_SIMULTANEOUSLY]->(:Person)\n(:Person)-[:MUST_PERFORM]->(:Procedure)\n(:Person)-[:BENEFICIARY_OF]->(:Will)\n(:Person)-[:CREATOR_OF]->(:Will)\n(:Person)-[:HAS_RIGHT]->(:Land)\n(:Person)-[:TRANSFER_STOCK]->(:Stock)\n(:Person)-[:OWN]->(:Property)\n(:Person)-[:MAKES_DISPOSITION_OF]->(:Asset)\n(:Person)-[:RECEIVES_DISPOSITION_OF]->(:Person)\n(:Person)-[:MAY_BE_DISCHARGED]->(:Consequence)\n(:Person)-[:MAY_BE_DISCHARGED]->(:Living Expenses)\n(:Person)-[:MAY_BE_DISCHARGED]->(:Action)\n(:Person)-[:MUST_NOTIFY]->(:Person)\n(:Person)-[:PERMITTED_TO_MAKE_CHANGES]->(:Person)\n(:Person)-[:OWNS]->(:Asset)\n(:Person)-[:DECEASED]->(:Body)\n(:Person)-[:HAS_AUTHORITY]->(:Responsibility)\n(:Person)-[:INHERITS]->(:Inheritance)\n(:Person)-[:IS_AFFECTED]->(:Property or Income)\n(:Person)-[:IS_LIABLE]->(:Compensation)\n(:Right)-[:OCCURS_WHEN]->(:Event)\n(:Right)-[:CAN_BE_EXERCISED_BY]->(:Party)\n(:Right)-[:APPLIES_TO]->(:Land)\n(:Contract)-[:IN_VOLUNTARY_CONTRACTING]->(:Employer)\n(:Document)-[:MENTIONS]->(:Clause)\n(:Document)-[:MENTIONS]->(:Law)\n(:Document)-[:MENTIONS]->(:Document)\n(:Document)-[:MENTIONS]->(:Entity)\n(:Document)-[:MENTIONS]->(:Age)\n(:Document)-[:MENTIONS]->(:Section)\n(:Document)-[:MENTIONS]->(:Insurer)\n(:Document)-[:MENTIONS]->(:Benefit)\n(:Document)-[:MENTIONS]->(:Assured)\n(:Document)-[:MENTIONS]->(:Contract)\n(:Document)-[:MENTIONS]->(:Right)\n(:Document)-[:MENTIONS]->(:Company)\n(:Document)-[:MENTIONS]->(:Person)\n(:Document)-[:MENTIONS]->(:Property)\n(:Document)-[:MENTIONS]->(:Event)\n(:Document)-[:MENTIONS]->(:Laws)\n(:Document)-[:MENTIONS]->(:Category)\n(:Document)-[:MENTIONS]->(:Assumption)\n(:Document)-[:MENTIONS]->(:Text)\n(:Document)-[:MENTIONS]->(:Code)\n(:Document)-[:MENTIONS]->(:Procedure)\n(:Document)-[:MENTIONS]->(:Law Section)\n(:Document)-[:MENTIONS]->(:Language)\n(:Document)-[:MENTIONS]->(:Court)\n(:Document)-[:MENTIONS]->(:Party)\n(:Document)-[:MENTIONS]->(:Concept)\n(:Document)-[:MENTIONS]->(:Regulation)\n(:Document)-[:MENTIONS]->(:Transaction)\n(:Document)-[:MENTIONS]->(:Employee)\n(:Document)-[:MENTIONS]->(:Employer)\n(:Document)-[:MENTIONS]->(:Order)\n(:Document)-[:MENTIONS]->(:Authority)\n(:Document)-[:MENTIONS]->(:Meeting)\n(:Document)-[:MENTIONS]->(:Article)\n(:Document)-[:MENTIONS]->(:Lawsuit)\n(:Document)-[:MENTIONS]->(:Organization)\n(:Document)-[:MENTIONS]->(:Will)\n(:Document)-[:MENTIONS]->(:Action)\n(:Document)-[:MENTIONS]->(:Content)\n(:Document)-[:MENTIONS]->(:Land)\n(:Document)-[:MENTIONS]->(:Cost)\n(:Document)-[:MENTIONS]->(:Stock)\n(:Document)-[:MENTIONS]->(:Condition)\n(:Document)-[:MENTIONS]->(:Agreement)\n(:Document)-[:MENTIONS]->(:Payment)\n(:Document)-[:MENTIONS]->(:Court Case)\n(:Document)-[:MENTIONS]->(:Time Period)\n(:Document)-[:MENTIONS]->(:Organisation)\n(:Document)-[:MENTIONS]->(:Asset)\n(:Document)-[:MENTIONS]->(:Notification)\n(:Document)-[:MENTIONS]->(:Article or Section)\n(:Document)-[:MENTIONS]->(:Laws and Regulations)\n(:Document)-[:MENTIONS]->(:Structure)\n(:Document)-[:MENTIONS]->(:Legislation)\n(:Document)-[:MENTIONS]->(:Body)\n(:Document)-[:MENTIONS]->(:Responsibility)\n(:Document)-[:MENTIONS]->(:Inheritance)\n(:Document)-[:MENTIONS]->(:Living Expenses)\n(:Document)-[:MENTIONS]->(:Consequence)\n(:Document)-[:MENTIONS]->(:Property or Income)\n(:Document)-[:MENTIONS]->(:Compensation)\n(:Document)-[:MENTIONS]->(:Legal Topic)\n(:Document)-[:MENTIONS]->(:Activity)\n(:Document)-[:MENTIONS]->(:Case)\n(:Document)-[:MENTIONS]->(:Agent)\n(:Document)-[:MENTIONS]->(:Business Activity)\n(:Document)-[:MENTIONS]->(:Partner)\n(:Document)-[:CONTAINS]->(:Section)\n(:Document)-[:CONTAINS]->(:Law Section)\n(:Document)-[:CONTAINS]->(:Clause)\n(:Document)-[:HAS_SECTION]->(:Section)\n(:Document)-[:REGULATES]->(:Legal Topic)\n(:Document)-[:DEFINES]->(:Law)\n(:Document)-[:DEFINES]->(:Authority)\n(:Document)-[:DEFINES]->(:Clause)\n(:Document)-[:INCLUDES]->(:Clause)\n(:Lawsuit)-[:CONTAINS]->(:Section)\n(:Lawsuit)-[:DEFINES]->(:Clause)\n(:Legislation)-[:CONTAINS]->(:Section)\n(:Legislation)-[:DEFINES]->(:Person)\n(:Legislation)-[:SPECIFIES]->(:Business Activity)\n(:Party)-[:HAS_RIGHT]->(:Right)\n(:Party)-[:SUBJECT_TO]->(:Law)\n(:Party)-[:MAY_WITHDRAW]->(:Asset)\n(:Party)-[:PARTICIPATES_IN]->(:Contract)\n(:Party)-[:HAS_PROPERTY]->(:Property)\n(:Party)-[:MUST_USE]->(:Laws)\n(:Party)-[:RECEIVES_COMPENSATION]->(:Payment)\n(:Party)-[:MAY_CANCEL]->(:Agreement)\n(:Party)-[:MAY_ACCEPT]->(:Asset)\n(:Court)-[:ISSUES_ORDER]->(:Order)\n(:Court)-[:AUTHORIZES]->(:Party)\n(:Employer)-[:OBLIGED_TO_PAY]->(:Employee)\n(:Organization)-[:DECIDES]->(:Person)\n(:Organization)-[:JUDGE_OVER]->(:Will)\n(:Language)-[:MUST_BE_INCLUDED]->(:Procedure)\n(:Entity)-[:MUST_BE_CONSULTED_BEFORE]->(:Entity)\n(:Entity)-[:IS_SUBJECT_TO]->(:Entity)\n(:Entity)-[:MUST_BE_AGE]->(:Age)\n(:Entity)-[:IS_RESPONSIBLE_FOR]->(:Entity)\n(:Assured)-[:CAN_CANCEL]->(:Contract)\n(:Assured)-[:MAY_RECEIVE_BENEFIT]->(:Benefit)\n(:Insurer)-[:CAN_CANCEL]->(:Contract)\n(:Insurer)-[:HAS_RIGHT]->(:Right)\n(:Company)-[:RELATED_TO]->(:Stock)\n(:Code)-[:MUST_HAVE_TRANSLATION]->(:Language)\n(:Law Section)-[:CONTAINS]->(:Procedure)\n(:Authority)-[:MAY_ORDER]->(:Action)\n(:Meeting)-[:AUTHORIZES]->(:Authority)\n(:Stock)-[:CAN_BE_TRANSFERRED]->(:Condition)\n(:Stock)-[:SUBCLASS_OF]->(:Stock)\n(:Agreement)-[:MAY_BE_CANCELLED]->(:Party)\n(:Court Case)-[:RELATED_TO]->(:Law)\n(:Organisation)-[:RECEIVES_NOTIFICATION]->(:Notification)\n(:Laws and Regulations)-[:RELATED_TO]->(:Article or Section)\n(:Agent)-[:HAS_AUTHORITY]->(:Law)'

In [6]:
from langchain_core.prompts.prompt import PromptTemplate

CYPHER_GENERATION_TEMPLATE = """
Task: Generate a Neo4j Cypher statement based on the provided schema to answer Thai legal questions.

Schema Context: {schema}
- Main Node: `Document` (Contains properties: `text`, `law_name`, `section_num`, `id`)
- Other Nodes: `Law`, `Clause`, `Section`, `Entity`, `Action`, `Party`, `Right`, etc.
- Primary Relationship: `(:Document)-[:MENTIONS]->(n)` (Use this to find related concepts or entities mentioned in a specific legal section)

Instructions:
1. Always start by filtering the `Document` node using `law_name` and `section_num` if provided in the question.
2. If the user asks for "บทลงโทษ" or specific details, use `d.text CONTAINS "..."` to filter the content.
3. [Crucial] To find related context or neighbors, traverse from the `Document` node using the `[:MENTIONS]` relationship to other labels like `Entity`, `Action`, or `Right`.
4. Use `OPTIONAL MATCH` for traversals to ensure the main document is returned even if no specific neighbors are found.
5. Return the main legal text along with a list of mentioned entities/concepts.

Example 1: (Filtering and Traversal)
Question: "ถ้ามีคนประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตต้องระวางโทษอย่างไร และเกี่ยวข้องกับใครหรืออะไรบ้าง"
Cypher:
MATCH (d:Document)
WHERE d.law_name CONTAINS "สัญญาซื้อขายล่วงหน้า" 
  AND d.text CONTAINS "ประกอบกิจการ" 
  AND d.text CONTAINS "ไม่ได้รับใบอนุญาต"
OPTIONAL MATCH (d)-[:MENTIONS]->(neighbor)
RETURN d.law_name, d.section_num, d.text, 
       collect(DISTINCT {{label: labels(neighbor)[0], id: neighbor.id}}) AS Mentions

Example 2: (Specific Section Search)
Question: "มาตรา 193 ของกฎหมายแพ่งและพาณิชย์ กล่าวถึงเรื่องอะไร"
Cypher:
MATCH (d:Document {{section_num: "193"}})
WHERE d.law_name CONTAINS "แพ่งและพาณิชย์"
OPTIONAL MATCH (d)-[:MENTIONS]->(m)
RETURN d.text, collect(labels(m)) AS RelatedCategories

Note: Do not include any text except the generated Cypher statement.
The question is: {question}
"""

CYPHER_GENERATION_PROMPT = PromptTemplate(
    input_variables=["schema", "question"], template=CYPHER_GENERATION_TEMPLATE
)

In [7]:
# 1. นิยาม Prompt สำหรับการสรุปคำตอบ (QA)
QA_TEMPLATE = """Task: คุณคือทนายความผู้เชี่ยวชาญ จงสรุปคำตอบจากข้อมูลที่ได้จากฐานข้อมูลกฎหมาย

Question: {question}

Context (ข้อมูลจาก Graph Database):
{context}

Instructions:
- นำเนื้อหาจาก 'd.text' มาตอบคำถามให้ชัดเจน
- หากมีการกล่าวถึงมาตราหรือแนวคิดที่เกี่ยวข้อง (Mentions/Neighbors) ให้สรุปมาด้วย
- ตอบเป็นภาษาไทยที่สุภาพ เป็นทางการ และเข้าใจง่าย
- หากข้อมูลใน Context ไม่เพียงพอ ให้แจ้งว่าไม่พบข้อมูลที่ระบุในระบบ

Answer:"""

MY_QA_PROMPT = PromptTemplate(
    input_variables=["context", "question"], 
    template=QA_TEMPLATE
)

In [8]:
chain = GraphCypherQAChain.from_llm(
    graph=graph,
    # llm= ChatOpenAI(temperature=0, model="anthropic/claude-haiku-4.5", api_key=os.getenv("openrouter_API_key"), base_url="https://openrouter.ai/api/v1"),
    cypher_llm=ChatOpenAI(temperature=0, model="anthropic/claude-haiku-4.5", api_key=os.getenv("openrouter_API_key"), base_url="https://openrouter.ai/api/v1"),
    qa_llm=ChatOpenAI(temperature=0, model="openai/gpt-4o-mini", api_key=os.getenv("openrouter_API_key"), base_url="https://openrouter.ai/api/v1"),
    verbose=True,
    top_k=10,
    return_direct=False,
    cypher_prompt=CYPHER_GENERATION_PROMPT,
    qa_prompt=MY_QA_PROMPT,
    # function_response_system="Respond as a bird that is a professional lawyer!",
    allow_dangerous_requests=True,
    # use_function_response=True,
)

In [ ]:
import time 

with get_openai_callback() as cb:
    start_time = time.perf_counter()

    response = chain.invoke({"query": "ถ้ามีคนประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตต้องระวางโทษอย่างไร"}) # bird lawyer
   
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"Elapsed time: {elapsed_time:.4f} seconds")

    print(f"คำถาม: {response['query']}")
    print(f"คำตอบ: {response['result']}")   
    print(f"Total Tokens: {cb.total_tokens}")
    print(f"Prompt Tokens: {cb.prompt_tokens}")
    print(f"Completion Tokens: {cb.completion_tokens}")

> Entering new GraphCypherQAChain chain...
Generated Cypher:
cypher
MATCH (d:Document)
WHERE d.law_name CONTAINS "สัญญาซื้อขายล่วงหน้า"
  AND d.text CONTAINS "ประกอบกิจการ"
  AND d.text CONTAINS "ไม่ได้รับใบอนุญาต"
OPTIONAL MATCH (d)-[:MENTIONS]->(neighbor)
RETURN d.law_name, d.section_num, d.text,
       collect(DISTINCT {label: labels(neighbor)[0], id: neighbor.id}) AS Mentions

Full Context:
[{'d.law_name': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', 'd.section_num': '132', 'd.text': 'กฎหมาย: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546\nมาตรา: 132\nเนื้อหา: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน', 'Mentions': [{'id': 'มาตรา 54', 'label': 'Clause'}, {'id': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546', 'label': 'Law'}, {'id': 'ใบอนุญาต', 'label': 'Document'}, {'id': 'มาตรา 132', 'label': 'Clause'}, {'id': 'ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54', 'label': 'Entity'}]}]

> Finished chain.
คำถาม: ถ้ามีคนประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตต้องระวางโทษอย่างไร
คำตอบ: ตามพระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ระบุว่า ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 จะต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ นอกจากนี้ยังมีโทษปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืนอยู่ด้วย

ดังนั้น หากมีการประกอบกิจการดังกล่าวโดยไม่มีใบอนุญาต จะต้องเผชิญกับโทษตามที่กฎหมายกำหนดข้างต้น.
Total Tokens: 7754
Prompt Tokens: 7422
Completion Tokens: 332

In [10]:
import time

with get_openai_callback() as cb:
    start_time = time.perf_counter()

    response = chain.invoke({"query": "ถ้าผู้ิยู่ในปกครองได้ยินยอมในการกระทำของผู้ปกครองจะทำให้ผู้ปกครองหลุดพ้นจากความรับผิดหรือเปล่า"})
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"Elapsed time: {elapsed_time:.4f} seconds")
    print(f"คำถาม: {response['query']}")
    print(f"คำตอบ: {response['result']}")   
    print(f"Total Tokens: {cb.total_tokens}")
    print(f"Prompt Tokens: {cb.prompt_tokens}")
    print(f"Completion Tokens: {cb.completion_tokens}")

> Entering new GraphCypherQAChain chain...
Generated Cypher:
cypher
MATCH (d:Document)
WHERE d.text CONTAINS "ผู้อยู่ในปกครอง"
  AND d.text CONTAINS "ยินยอม"
  AND d.text CONTAINS "ผู้ปกครอง"
  AND d.text CONTAINS "ความรับผิด"
OPTIONAL MATCH (d)-[:MENTIONS]->(entity:Entity)
OPTIONAL MATCH (d)-[:MENTIONS]->(action:Action)
OPTIONAL MATCH (d)-[:MENTIONS]->(responsibility:Responsibility)
OPTIONAL MATCH (d)-[:MENTIONS]->(consequence:Consequence)
RETURN d.law_name, d.section_num, d.text,
       collect(DISTINCT {label: "Entity", id: entity.id}) AS Entities,
       collect(DISTINCT {label: "Action", id: action.id}) AS Actions,
       collect(DISTINCT {label: "Responsibility", id: responsibility.id}) AS Responsibilities,
       collect(DISTINCT {label: "Consequence", id: consequence.id}) AS Consequences

Full Context:
[{'d.law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์', 'd.section_num': '1598/5', 'd.text': 'กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nมาตรา: 1598/5\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5\nถ้าผู้อยู่ในปกครองรู้จักผิดชอบและมีอายุไม่ต่ำกว่าสิบห้าปีบริบูรณ์เมื่อผู้ปกครองจะทำกิจการใดที่สำคัญ ให้ปรึกษาหารือผู้อยู่ในปกครองก่อนเท่าที่จะทำได้\nการที่ผู้อยู่ในปกครองได้ยินยอมด้วยนั้นหาคุ้มผู้ปกครองให้พ้นจากความรับผิดไม่', 'Entities': [{'id': 'ผู้ปกครอง', 'label': 'Entity'}, {'id': 'ผู้อยู่ในปกครอง', 'label': 'Entity'}], 'Actions': [{'id': None, 'label': 'Action'}], 'Responsibilities': [{'id': None, 'label': 'Responsibility'}], 'Consequences': [{'id': None, 'label': 'Consequence'}]}]

> Finished chain.
Elapsed time: 8.7320 seconds
คำถาม: ถ้าผู้ิยู่ในปกครองได้ยินยอมในการกระทำของผู้ปกครองจะทำให้ผู้ปกครองหลุดพ้นจากความรับผิดหรือเปล่า
คำตอบ: ตามที่ระบุในประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5 ระบุว่า หากผู้อยู่ในปกครองมีอายุไม่ต่ำกว่าสิบห้าปีบริบูรณ์และรู้จักผิดชอบ ผู้ปกครองจะต้องปรึกษาหารือกับผู้อยู่ในปกครองก่อนที่จะทำกิจการใดที่สำคัญ อย่างไรก็ตาม การที่ผู้อยู่ในปกครองได้ยินยอมในการกระทำของผู้ปกครองนั้น ไม่สามารถทำให้ผู้ปกครองหลุดพ้นจากความรับผิดชอบได้

ดังนั้น คำตอบคือ ผู้ปกครองจะไม่หลุดพ้นจากความรับผิดแม้ว่าผู้อยู่ในปกครองจะได้ยินยอมในการกระทำของผู้ปกครองก็ตาม
Total Tokens: 7835
Prompt Tokens: 7367
Completion Tokens: 468

### VectorRetriever

In [56]:
from neo4j_graphrag.retrievers import VectorRetriever, VectorCypherRetriever, Text2CypherRetriever

In [ ]:
# # Initialize the retriever
# embedder = OpenAIEmbeddings(api_key=openai_api_key, model="")

# retriever = VectorRetriever(
#      driver,
#      index_name= "text_embeddings",
#      embedder=embedder,
#      return_properties=["text"]
# )
# query = "What are the main risks around cryptocurrency?"
# result = retriever.search(query_text=query, top_k=10)

### VectorCypherRetriever

In [ ]:
# vector_cypher_retriever = VectorCypherRetriever(
#     driver=driver,
#     index_name='chunkEmbeddings',
#     embedder=embedder,
#     retrieval_query=chunk_to_asset_manager_query
# )

In [ ]:
# result = GraphRag(llm=llm,retriever=vector_cyper_retriever)
# print(rag.search(query_text=query_text).answer)